[package]
name = "libliquidfun-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = "*"
cxx = "*"

[build-dependencies]
autocxx-build = "*"
cmake = "0.1.50"
cc = "*"
